r_bn:  10.0
lr:  0.25
r_wb:  0.0
bc loaded
bc shape (10, 10, 192)
Traceback (most recent call last):
  File "data_synthesis_new.py", line 420, in <module>
    main_syn(args, bc)
  File "data_synthesis_new.py", line 285, in main_syn
    model_teacher = prepare_model(args)
  File "data_synthesis_new.py", line 46, in prepare_model
    checkpoint = torch.load(args.ckpt_path)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../pretrain/output/imagenette_ViT/214/model_49.pth'
=> using pytorch pre-trained model 'ViT'
Traceback (most recent call last):
  File "generate_soft_label.py", line 253, in <module>
    main()
  File "generate_soft_label.py", line 126, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "generate_soft_label.py", line 154, in main_worker
    checkpoint = torch.load(args.ckpt_path)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../pretrain/output/imagenette_ViT/214/model_49.pth'
Traceback (most recent call last):
  File "train_FKD.py", line 367, in <module>
    main()
  File "train_FKD.py", line 103, in main
    train_dataset = ImageFolder_FKD_MIX(
  File "/media/techt/One Touch/DD/SRe2L/train/../relabel/utils_fkd.py", line 155, in __init__
    super(ImageFolder_FKD_MIX, self).__init__(**kwargs)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
  File "/home/techt/anaconda3/envs/hl/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in ../recover/syn_data/imagenette/802.
